#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 加载 NVM 环境
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# 类型检查
bunx tsgo --incremental --noEmit || exit $?

# 代码格式化、linting
bunx lint-staged
